kube-prometheus-stack:
  alertmanager:
    alertmanagerSpec:
      image:
        registry: quay.io
        repository: prometheus/alertmanager
        tag: v0.27.0
    ingress:
      enabled: true
      hosts:
        - alertmanager-prod.localhost
      paths:
        - /
  grafana:
    image:
      tag: 11.2.1
    adminPassword: admin
    sidecar:
      dashboards:
        enabled: true
        labelValue: ""
    ingress:
      enabled: true
      hosts:
        - grafana-prod.localhost
      paths:
        - /
  prometheus:
    prometheusSpec:
      image:
      registry: quay.io
      repository: prometheus/prometheus
      tag: v2.55.1
    ingress:
      enabled: true
      hosts:
        - prometheus-prod.localhost
      paths:
        - /
  prometheus-node-exporter:
    prometheus:
      monitor:
        interval: 15s