kube-prometheus-stack:
  alertmanager: 
    ingress:
      enabled: true
      hosts:
        - alertmanager-prod.localhost
      paths:
        - /
  grafana:
    adminPassword: admin
    sidecar:
      dashboards:
        enabled: true
        labelValue: ""
    ingress:
      enabled: true
      hosts:
        - grafana-prod.localhost
      paths:
        - /
  prometheus:
    ingress:
      enabled: true
      hosts:
        - prometheus-prod.localhost
      paths:
        - /
  prometheus-node-exporter:
    prometheus:
      monitor:
        interval: 15s