kube-prometheus-stack:
  alertmanager:
    alertmanagerSpec:
      image:
        tag: v0.28.1
    ingress:
      enabled: true
      hosts:
        - alertmanager-prod.localhost
      paths:
        - /
  grafana:
    image:
      tag: 12.0.1
    adminPassword: admin
    sidecar:
      dashboards:
        enabled: true
        labelValue: ""
    ingress:
      enabled: true
      hosts:
        - grafana-prod.localhost
      paths:
        - /
  prometheus:
    prometheusSpec:
      image:
        tag: v3.4.1
    ingress:
      enabled: true
      hosts:
        - prometheus-prod.localhost
      paths:
        - /
  prometheus-node-exporter:
    prometheus:
      monitor:
        interval: 15s
