#!/usr/bin/env bash
set -euo pipefail

for f in appsets/*.yaml; do
  name=$(basename "$f" .yaml)
  echo "Generating argocd/${name}.yaml from $f"
  echo "# Auto-generated by generate-apps.sh — do not edit manually" > "argocd/${name}.yaml"
  argocd appset generate "$f" -o yaml --grpc-web --server "$ARGOCD_SERVER" --auth-token "$TOKEN" \
    | yq '.[]' - \
    | sed 's/^apiVersion/---\napiVersion/' >> "argocd/${name}.yaml"
done
