apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: prometheus-is-up
  namespace: kargo-helm-prom-stack
spec:
  metrics:
  - name: prometheus-is-up
    interval: 10s
    count: 6
    successCondition: result[0] < 1
    failureLimit: 1
    provider:
      prometheus:
        address: http://kube-prometheus-stack-prometheus.monitoring.svc:9090
        insecure: true
        timeout: 40
        query: |
          sum(kube_pod_status_phase{namespace='monitoring',phase!='Running',pod=~".*kube-prometheus-stack.*"}) by (pod)