apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: is-up-prometheus
  namespace: kargo-helm-prom-stack
spec:
  metrics:
  - name: success-rate
    interval: 5m
    successCondition: result[0] >= 1
    failureLimit: 3
    provider:
      prometheus:
        address: http://kube-prometheus-stack-prometheus.monitoring.svc:9090
        insecure: true
        timeout: 40
        query: |
          sum(up{pod=~'prometheus-kube-prometheus-stack-prometheus-.*'}) by (pod)
