apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: prometheus-is-up
  namespace: kargo-helm-prom-stack
spec:
  metrics:
  - name: prometheus-is-up
    interval: 30s
    count: 4
    successCondition: result[0] >= 1
    failureLimit: 3
    provider:
      prometheus:
        address: http://kube-prometheus-stack-prometheus.monitoring.svc:9090
        insecure: true
        timeout: 40
        query: |
          sum(up{namespace='monitoring'}) by (pod)
