apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-helm-prom-stack
  namespace: kargo-helm-prom-stack
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: kargo-helm-prom-stack
  namespace: kargo-helm-prom-stack
spec:
  promotionPolicies:
    - autoPromotionEnabled: true
      stage: dev
    - autoPromotionEnabled: true
      stage: test
    - autoPromotionEnabled: false
      stage: prod
