apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-helm-prom-stack
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  promotionPolicies:
  - stage: dev
    autoPromotionEnabled: false
