apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    rbac.kargo.akuity.io/claim.groups: argocd-dev
  name: kargo-promote-non-prod
  namespace: kargo-helm-prom-stack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kargo-promote-non-prod
  namespace: kargo-helm-prom-stack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kargo-promote-non-prod
subjects:
- kind: ServiceAccount
  name: kargo-promote-non-prod
  namespace: kargo-helm-prom-stack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kargo-promote-non-prod
  namespace: kargo-helm-prom-stack
rules:
- apiGroups:
  - argoproj.io
  resources:
  - analysisruns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - analysistemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kargo.akuity.io
  resources:
  - freights
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kargo.akuity.io
  resources:
  - promotions
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - kargo.akuity.io
  resourceNames:
  - dev
  resources:
  - stages
  verbs:
  - get
  - list
  - promote
  - watch
- apiGroups:
  - kargo.akuity.io
  resourceNames:
  - test
  resources:
  - stages
  verbs:
  - get
  - list
  - promote
  - watch
- apiGroups:
  - kargo.akuity.io
  resources:
  - warehouses
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - get
  - list
  - watch
