apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kube-prometheus-stack
  namespace: kargo-helm-prom-stack
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  freightCreationPolicy: Automatic
  interval: 5m0s
  subscriptions:
    - chart:
        discoveryLimit: 10
        name: kube-prometheus-stack
        repoURL: https://prometheus-community.github.io/helm-charts
        semverConstraint: ">=75.0.0"

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: grafana
  namespace: kargo-helm-prom-stack
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  freightCreationPolicy: Automatic
  interval: 5m0s
  subscriptions:
    - image:
        discoveryLimit: 10
        repoURL: docker.io/grafana/grafana
        imageSelectionStrategy: SemVer
        semverConstraint: ">=12.0.0"
        strictSemvers: true

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: alertmanager
  namespace: kargo-helm-prom-stack
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  freightCreationPolicy: Automatic
  interval: 5m0s
  subscriptions:
  - image:
      discoveryLimit: 10
      repoURL: quay.io/prometheus/alertmanager
      imageSelectionStrategy: SemVer
      semverConstraint: ">=0.28.0"
      strictSemvers: true

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: prometheus
  namespace: kargo-helm-prom-stack
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  freightCreationPolicy: Automatic
  interval: 5m0s
  subscriptions:
  - image:
      discoveryLimit: 10
      repoURL: quay.io/prometheus/prometheus
      imageSelectionStrategy: SemVer
      semverConstraint: ">=3.4.0"
      strictSemvers: true
