apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kube-prometheus-stack
  namespace: kargo-helm-prom-stack
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  freightCreationPolicy: Automatic
  interval: 5m0s
  subscriptions:
    - chart:
        discoveryLimit: 5
        name: kube-prometheus-stack
        repoURL: https://prometheus-community.github.io/helm-charts

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: grafana
  namespace: kargo-helm-prom-stack
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  freightCreationPolicy: Automatic
  interval: 5m0s
  subscriptions:
    - image:
        discoveryLimit: 5
        repoURL: docker.io/grafana/grafana
        imageSelectionStrategy: SemVer
        strictSemvers: true

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: alertmanager
  namespace: kargo-helm-prom-stack
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  freightCreationPolicy: Automatic
  interval: 5m0s
  subscriptions:
  - image:
      discoveryLimit: 5
      repoURL: quay.io/prometheus/alertmanager
      imageSelectionStrategy: SemVer
      strictSemvers: true

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: prometheus
  namespace: kargo-helm-prom-stack
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  freightCreationPolicy: Automatic
  interval: 5m0s
  subscriptions:
  - image:
      discoveryLimit: 5
      repoURL: quay.io/prometheus/prometheus
      imageSelectionStrategy: SemVer
      strictSemvers: true
