apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service-monitors.yaml

configMapGenerator:
  - name: akuity-dashboard
    files:
    - akuity-dashboard.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: akuity-dashboard

patches:
- patch: |
    - op: replace
      path: /metadata/namespace
      value: monitoring
  target:
    kind: ConfigMap
    name: akuity-dashboard