apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kargo-addons
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: "*"
    kind:  '*'
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
  roles:
    - description: Role used for AppSet generation
      name: appset-generate
      policies:
        - p, proj:kargo-addons:appset, applications, get, kargo-addons/*, allow
        - p, proj:kargo-addons:appset, applicationsets, *, kargo-addons/*, allow
        - p, proj:kargo-addons:appset, clusters, get, kargo-addons/*, allow
        - p, proj:kargo-addons:appset, repositories, get, kargo-addons/*, allow
