apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kargo-helm
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/34fathombelow/kargo-helm-prom-stack.git
