apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-helm-prom-stack
spec:
  project: kargo-helm
  source:
    repoURL: https://github.com/34fathombelow/kargo-helm-prom-stack.git
    targetRevision: expression_lang
    path: kargo
  destination:
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true