apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kube-prometheus-stack
  namespace: kargo-helm-prom-stack
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  freightCreationPolicy: Automatic
  interval: 5m0s
  subscriptions:
    - chart:
        discoveryLimit: 5
        name: kube-prometheus-stack
        repoURL: https://prometheus-community.github.io/helm-charts
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: addon-extras
  namespace: kargo-helm-prom-stack
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  freightCreationPolicy: Automatic
  interval: 5m0s
  subscriptions:
    - git:
        branch: main
        commitSelectionStrategy: NewestFromBranch
        discoveryLimit: 5
        expressionFilter: "!(author contains 'Kargo')"
        repoURL: https://github.com/34fathombelow/kargo-helm-prom-stack.git
        includePaths:
        - addons/kube-prometheus-stack/extras
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: non-operator-images
  namespace: kargo-helm-prom-stack
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  freightCreationPolicy: Automatic
  interval: 5m0s
  subscriptions:
  - image:
      allowTagsRegexes:
      - ^v[0-9]+\.[0-9]+\.[0-9]+$
      discoveryLimit: 5
      repoURL: quay.io/prometheus/prometheus
      imageSelectionStrategy: SemVer
      strictSemvers: true
  - image:
      allowTagsRegexes:
      - ^[0-9]+\.[0-9]+\.[0-9]+$
      discoveryLimit: 5
      imageSelectionStrategy: SemVer
      repoURL: docker.io/grafana/grafana
      strictSemvers: true
  - image:
      allowTagsRegexes:
      - ^v[0-9]+\.[0-9]+\.[0-9]+$
      discoveryLimit: 5
      repoURL: quay.io/prometheus/alertmanager
      imageSelectionStrategy: SemVer
      strictSemvers: true
