kube-prometheus-stack:
  alertmanager:
    alertmanagerSpec:
      image:
        tag: v0.27.0
    ingress:
      enabled: true
      hosts:
        - alertmanager-dev.localhost
      paths:
        - /
  grafana:
    image:
      tag: 11.3.1
    adminPassword: admin
    sidecar:
      dashboards:
        enabled: true
        labelValue: ""
    ingress:
      enabled: true
      hosts:
        - grafana-dev.localhost
      paths:
        - /
  prometheus:
    prometheusSpec:
      image:
        tag: v3.0.1
    ingress:
      enabled: true
      hosts:
        - prometheus-dev.localhost
      paths:
        - /
  prometheus-node-exporter:
    prometheus:
      monitor:
        interval: 15s
